ueberauth/oauth2

lib/oauth2/strategy/auth_code.ex

This modifies the reference link for the Authorization Code Strategy to point
to the official RFC rather than the section in the original draft.

Link to the official oauth2 rfc in AuthCode

---

lib/oauth2/util.ex

:erlang.now has been deprecated in erlang 18, so have changed the single
use to use :os.timestamp instead.

Replace erlang.now with os.timestamp

---

lib/oauth2/access_token.ex

@scrogson Thanks for this library!
I find it awkward that I have to use another library to make api calls, since via oauth2 I can only make GET requests? I have exposed PUT/POST and left generic request so one can make also others if needed. I did not add DELETE/HEAD before discussing the idea with you.
AccessToken.post/post!...    
AccessToken.put/put!...
The other thing, I was missing option to set default headers in requests, so now if you put the header on the client, it is asumed in all: 
def client...
OAuth2.new([
....
]) |> put_header("Content-Type", "application/json")
end
As a side note: the docs of oauth2 are not so clear regarding one thing. I was scratching my head what to do with the access_token that is persisted - how to make a AccessToken struct out of it again to use in …

POST/PUT methods via generic request with the access token, and possibility for default headers 

---

lib/oauth2/response.ex

If the response body is empty, it should not even be attempted to be decoded. This is a case for example in delete requests where no content body would be returned. The same allows keeping default headers content type for all other requests.

empty body should not be decoded

---

config/config.exs
config/dev.exs
config/test.exs
lib/oauth2/access_token.ex
lib/oauth2/request.ex
lib/oauth2/response.ex
mix.exs
mix.lock
test/oauth2/access_token_test.exs
test/oauth2/strategy/auth_code_test.exs
test/oauth2/strategy/client_credentials_test.exs
test/oauth2/strategy/password_test.exs
test/oauth2_test.exs
test/support/consumer_router.ex
test/support/provider_router.ex
test/support/test_helpers.ex
test/test_helper.exs

This PR improves the ability to pattern match on the results coming back from a provider.
Previously, you would only get back the body. Now you will get back an `{:ok, %OAuth2.Response{}}`.
So you can do something like:
```elixir
case OAuth2.AccessToken.get(token, "/me") do
{:ok, %OAuth2.Response{status: 401}} ->
...
end
```

Simplify the response handling.

---

mix.exs

Otherwise it breaks if any of your dependencies is using poison 2.0 or 2.1
I ran the tests with 2.1 and it passes.

Allow poison ~> 2.0

---

lib/oauth2/access_token.ex
test/oauth2/strategy/client_credentials_test.exs

On normal flow from client credentials, the client is sending tow `Authorization` headers to my api client one with the correct `Bearer` content, other with the client header `Basic`, which was created to get the bearer token. This causes confusion on my API provider assumes the Basic token is the one that has to be validated causing an invalid type error.
Ex of my flow
```elixir
client = OAuth2.Client.new([
strategy: OAuth2.Strategy.ClientCredentials,
client_id: @client_id,
client_secret: @client_secret,
site: @site,
token_url: @token_url
])
token = client.get_token!(client)
OAuth2.AccessToken.get!(token, "/users") # sending two Authorization headers
```

Access token sending two Authentication headers

---

README.md

Bump the version to 0.6 in the instructions on how to add a new dependency.

Fixing version number in README

---

lib/oauth2/access_token.ex
test/oauth2/access_token_test.exs

This forces both string and integer values for expires in to parse to an
integer that is added to unix_now, while leaving expires to simply be
parsed to an integer.
Fixes #58

Parse expires_in to future timestamp

---

lib/oauth2/access_token.ex
lib/oauth2/client.ex
lib/oauth2/response.ex
test/oauth2/access_token_test.exs
test/oauth2/client_test.exs

Cleans up some documentation after the refactor in #52 .
I cleaned up some of the changes around the split out of the Client module. Documentation probably still needs to be written to migrate from 0.6 to 0.7.
I also added some doctests to make sure parts of the documentation stay up to date, feel free to remove them if you don't like them.
Related #60

Documentation Cleanup

---

lib/oauth2/client.ex

Per the docs for hackney (https://github.com/benoitc/hackney/blob/master/doc/hackney.md) the option for setting the timeout is `recv_timeout` instead of `timeout`

Documentation update for network timeout

---

lib/oauth2/access_token.ex
test/oauth2/access_token_test.exs
test/support/test_helpers.ex

Normalized `expires` and `expires_in` to act the same if present in a callback.
However I'm a bit confused if we really should do this.... Especially looking at the changes in tests. What do you guys think? 
And I think in case of Facebook not working correctly it was the case of using v1.0 version of their API. Right now I can see someone create a PR to use v2.8 and I guess there is a correct field `expires_in` being sent in a callback. (https://github.com/ueberauth/ueberauth_facebook/pull/27)

normalized expires and expires_in 

---

lib/oauth2/access_token.ex

I get that when compiling dependencies (that include oauth2) for a 1.4
warning: variable "unix_now" does not exist and is being expanded to "unix_now()", please use parentheses to remove the ambiguity or change the variable name
lib/oauth2/access_token.ex:82
warning: variable "unix_now" does not exist and is being expanded to "unix_now()", please use parentheses to remove the ambiguity or change the variable name
lib/oauth2/access_token.ex:95

Fix compile time warnings with Elixir 1.4

---

lib/oauth2/request.ex
lib/oauth2/response.ex
lib/oauth2/serializer.ex
test/serializer_test.exs

Oauth2 silently ignores misconfigutration and just skips de/serialization of content. This lead me to long hours of debugging when all I needed was to add oauth2 application to the started applications in my mix file.
This pull request differentiate the case where a serializer for particular type is missing, indicated by a map without a value for that mime type and the case where the whole map is missing. If the whole map is missing it means something is not configured right, very likely oauth2 is missing from the mix file. Especially since this library can be a few of dependencies down, raising the misconfiguration problem as early as possible can help save time debugging.

Raise exception when serializers configuration is missing

---

lib/oauth2/client.ex

Dialyzer complains about the `get_token/4` and `get_token!/4` functions, because the typespec says that the `params` argument is supposed to be a map with binary keys, whereas `OAuth2.Strategy.AuthCode.get_token/3` expects `params` to be a Keyword list.
Code:
```elixir
client()
|> OAuth2.Client.get_token!([code: code], [], [])
|> OAuth2.Client.get!("/user")
```
Dialyzer's complaint:
```
git_hub.ex:60: The call 'Elixir.OAuth2.Client':'get_token!'(#{'__struct__':='Elixir.OAuth2.Client', 'authorize_url':=binary(), 'client_id':=binary(), 'client_secret':=binary(), 'headers':=[{binary(),binary()}], 'params':=#{binary()=>binary() | [binary() | [any()] | map()] | #{binary()=>binary() | [any()] | map()}}, 'redirect_uri':=binary(), 'site':=binary(), 'strategy':=atom(), 'token':='nil' | …
```

Fix dialyzer warning on @type params

---

lib/oauth2/client.ex
test/oauth2/client_test.exs

In some cases (e.g. google) the server does not return a refresh token. Since oauth2 has one struct that represents both refresh_token and access_token, it makes sense to return the same refresh token unless overridden by the response.

Return same refresh_token unless provided new one

---

lib/oauth2/util.ex
test/oauth2/util_test.exs

Microsoft's Azure AD v2.0 token endpoint responds with a Content-Type
containing multiple parameters, but the previous code only processes
cases with a content type, with or without a single parameter.

Fix handling of Content-Types with multiple params

---

lib/oauth2/client.ex
test/oauth2/client_test.exs

Updates the `OAuth2.Client.get_token!` function to handle error OAuth2.Response structs. I sent some incomplete data to Facebook Graph and saw this error bubble up:
```
[error] %ArgumentError{message: "raise/1 expects a module name, string or exception as the first argument, got: %OAuth2.Response{body: %{\"error\" => %{\"code\" => 101, \"fbtrace_id\" => \"Eelth+pfiU9\", \"message\" => \"Missing client_id parameter.\", \"type\" => \"OAuthException\"}}, headers: [{\"www-authenticate\", \"OAuth \\\"Facebook Platform\\\" \\\"invalid_client\\\" \\\"Missing client_id parameter.\\\"\"}, {\"access-control-allow-origin\", \"*\"}, {\"pragma\", \"no-cache\"}, {\"cache-control\", \"no-store\"}, {\"x-fb-rev\", \"3349395\"}, {\"content-type\", \"application/json\"}, {\"x-fb-trace-id\", …
```

Update OAuth2.Client.get_token! errors

---

lib/oauth2/client.ex

`Request.request/6` returns `{:error, Error.t}` for HTTP error and `{:error, Response.t}` for non-successful HTTP response.
Add missing `{:error, Response.t}` to `@spec`

Add missing spec for get_token

---

lib/oauth2/access_token.ex

It looks like [`%{}` stands for only "empty" maps in typespecs](https://hexdocs.pm/elixir/typespecs.html#literals) (whereas it can match for "any" maps on pattern matches).
So, currently codes like below are warned by dialyzer:
```ex
defp ensure_admin_domain(%OAuth2.AccessToken{other_params: %{"id_token" => id_token}}) do
end
defp ensure_admin_domain(otherwise) do
{:error, :id_token_not_found}
end
```
```
$ mix dialyze # Using https://github.com/fishcakez/dialyze
Finding applications for analysis
Finding suitable PLTs
Looking up modules in dialyze_erlang-20.0_elixir-1.5.3_deps-dev.plt
Finding applications for dialyze_erlang-20.0_elixir-1.5.3_deps-dev.plt
Finding modules for dialyze_erlang-20.0_elixir-1.5.3_deps-dev.plt
Checking 1725 modules in dialyze_erlang-20.0_elixir-1.5.3_deps-dev.plt …
```

Changes `%{}` into correct map type specifications

---

mix.exs

***Description:***
- relax hackney requirements
- I didn't increase to `1.10.1` and `1.11.0` deliberately as there are some issues with those versions of hackney in the hackney issues list. But I can include them if needed.

specify hackney requirements

---

lib/oauth2/client.ex

This should close https://github.com/scrogson/oauth2/issues/119
Looks like `get_token` was already correct, and it's just `refresh_token` that was missing the annotation :)

Fix typespecs for OAuth2.Client.refresh_token

---

mix.exs

This pull request relaxes the version requirements for Hackney same as #121, but that seems to have been abandoned with Travis failing. Unless there are any objections I have overlooked, I would love to see this merged and pushed to Hex.

Relax hackney version requirement

---

lib/oauth2/request.ex

Log the request in debug mode 

---

lib/oauth2/strategy.ex

Calling `use OAuth2.Strategy` will automatically specify it as a `behaviour` now

Auto-specify Behaviour

---

lib/oauth2/response.ex
test/oauth2/response_test.exs

If there is a serializer for a specified content type, it should always be used to parse the response body.
Fix #133

Always parse body by serializer if it exists

---

lib/oauth2/strategy/auth_code.ex
lib/oauth2/strategy/client_credentials.ex
lib/oauth2/strategy/password.ex
lib/oauth2/strategy/refresh.ex
test/oauth2/client_test.exs
test/oauth2/strategy/auth_code_test.exs
test/oauth2/strategy/password_test.exs
test/oauth2/strategy/refresh_test.exs

Fixes #128 
cc: @robotlovesyou

Add basic auth to AuthCode.get_token

---

lib/oauth2/response.ex

The response body can also be a list, which is currently not reflected in the type.

fix body type

---

lib/oauth2/client.ex

The PR provides a simple fix to the following type spec issue related to `OAuth2.Client.params()`
The spec for `OAuth2.Client.params()` is currently defined as:
```ex
@type params :: %{binary => param} | Keyword.t()
``` 
However, the default value for  `OAuth2.Client.params()` is an empty map `%{}`:
https://github.com/ueberauth/oauth2/blob/9b46f39503b0cc12a96a3b64e860276176680211/lib/oauth2/client.ex#L72
This gives rise to `Hammox.TypeMatchError` in tests:
```ex
** (Hammox.TypeMatchError) 
1st argument value %OAuth2.Client{authorize_url: "/o/oauth2/v2/auth", client_id: "__REDACTED__", client_secret: "__REDACTED__", headers: [{"content-type", "application/x-www-form-urlencoded"}], params: %{}, redirect_uri: "__REDACTED__", ref: nil, request_opts: [], serializers: %{"application/json" => …
```

fix client params typespec issue

---

README.md

This shouldn't be necessary to explicitly add `oauth2` as an application. Since [Elixir 1.9](https://elixir-lang.org/blog/2019/06/24/elixir-v1-9-0-released/) releases package up all dependences and their transitive dependencies. `Oauth2` has no application callback, so it shouldn't be needed

Remove applications step in install

---

CHANGELOG.md
lib/oauth2/client.ex
mix.exs
test/oauth2/client_test.exs

Fixes https://github.com/ueberauth/oauth2/issues/165
See OAuth spec Section 4.1.4. Previously, accept header would be set to
match the content type of the request, which is
application/x-www-form-urlencoded.

Add "Accept: application/json" header by default for get_token

---

lib/oauth2/error.ex

Currently when running `mix docs` we get [some](https://github.com/ueberauth/oauth2/actions/runs/3824203056#:~:text=client.ex%23L445-,documentation%20references%20type%20%22OAuth2.Error.t()%22%20but%20it%20is%20hidden%20or%20private,-hex%2Dpublish%20/%20Publish) [warnings](https://github.com/ueberauth/oauth2/actions/runs/3824203056/jobs/6506134600#step:3:311). It also happens when referring `OAuth2.Error.t()` from other projects.
```
warning: documentation references type "OAuth2.Error.t()" but it is hidden or private
lib/oauth2/client.ex:350: OAuth2.Client.refresh_token!/4
```
This PR solves this by making `OAuth2.Error` public in the docs while keeping `OAuth2.Error.message/1` undocumented.

remove warnings from mix docs

---

lib/oauth2/strategy/auth_code.ex

I find the existing documentation for `OAuth2.Strategy.AuthCode.authorize_url/2` rather vague/confusing.
If my understanding of its responsibility is correct, this is an attempt to improve its documentation.

[docs] Reword `OAuth2.Strategy.AuthCode.authorize_url/2` docs
